### ISSUE TITLE
Runtime warnings in Loewe problems

### ISSUE THREAD

**Issue by mjowen** [CardiacModelling/ionBench#1]
Some runtime warnings get triggered with the Loewe problems and sometimes Moreno (although Moreno may now be fixed)
Loewe has had some problems with stability. I had thought this was due to the negative tau values that some parameters could give resulting in unbounded probabilities and therefore current. 

My best guess is that there issues come from the .mmt files ODE calculation. for example exp(V/a) where a can be 0.

Not sure yet if these warnings actually break anything

Strict bounds on the parameters may fix this, or atleast reveal if this is the issue

The final line of IKur would suggest that the model is still blowing up

```
Loewe 2016 IKr
<string>:19: RuntimeWarning: overflow encountered in exp
<string>:22: RuntimeWarning: divide by zero encountered in scalar divide
<string>:20: RuntimeWarning: overflow encountered in exp

Loewe 2016 IKur
<string>:32: RuntimeWarning: divide by zero encountered in scalar divide
<string>:32: RuntimeWarning: overflow encountered in exp
<string>:39: RuntimeWarning: divide by zero encountered in scalar divide
C:\Users/pmzmo/OneDrive - The University of Nottingham/Documents/Python/ionBench\ionbench\benchmarker\benchmarker.py:61: RuntimeWarning: overflow encountered in square
  self.paramRMSRE.append(np.sqrt(np.mean(((estimatedParams-trueParams)/trueParams)**2)))
```

**Comment by mirams** [comment]
Yeah, those probably need some sensible parameter bounds to keep exponentials sensible, unless it is the 'GHK-like' problem we fixed in https://wellcomeopenresearch.org/articles/6-261 which can happen even with well behaved params, but only tends to happen with equations that feature `1/ (1 - exp(x))` which I don't think these IKr, IKur models will have.

**Comment by mjowen** [comment]
I have made some improvements to the myokit files. Some issues were GHK-like while others are a bit messier. They're all now captured in 'if's and 'piecewise's in the .mmt files. Unfortunately, myokit seems to evaluate all components in an 'if' statement rather than just condition and then the relevant part (eg if(a==0, 1, a/a) will still cause warnings from resolving the 0/0 even if it won't be used). This has at least made it so that the model fails to solve less frequently.

**Comment by mjowen** [comment]
Runtime warnings are unavoidable. A fix in myokit [here](https://github.com/myokit/myokit/pull/1060) ensures model is still solved when possible.
